<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Lease Contract</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #333;
            line-height: 1.6;
            margin: 40px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #1e293b;
            margin: 0;
            font-size: 28px;
        }
        .header p {
            color: #64748b;
            margin: 5px 0 0 0;
        }
        .content {
            margin-bottom: 40px;
        }
        .section-title {
            font-weight: bold;
            font-size: 18px;
            color: #0f172a;
            border-bottom: 1px solid #cbd5e1;
            padding-bottom: 5px;
            margin-top: 30px;
            margin-bottom: 15px;
        }
        .details-table {
            width: 100%;
            border-collapse: collapse;
        }
        .details-table td {
            padding: 8px 0;
            vertical-align: top;
        }
        .details-table td:first-child {
            width: 35%;
            font-weight: bold;
            color: #475569;
        }
        .terms p {
            text-align: justify;
            margin-bottom: 10px;
        }
        .signatures {
            margin-top: 60px;
            width: 100%;
        }
        .signature-box {
            width: 45%;
            display: inline-block;
        }
        .signature-line {
            border-bottom: 1px solid #000;
            height: 60px;
            margin-bottom: 10px;
        }
        .signature-img {
            max-height: 50px;
            max-width: 100%;
        }
    </style>
</head>
<body>

    <div class="header">
        <h1>RESIDENTIAL LEASE AGREEMENT</h1>
        <p>Generated by AbangHub on {{ now()->format('F d, Y') }}</p>
    </div>

    <div class="content">
        <p>This Lease Agreement is made and entered into on <strong>{{ $lease->signed_at ? $lease->signed_at->format('F d, Y') : now()->format('F d, Y') }}</strong>, between the Landlord and the Tenant named below.</p>

        <div class="section-title">1. PARTIES</div>
        <table class="details-table">
            <tr>
                <td>Landlord:</td>
                <td>{{ $lease->property->owner->full_name ?? $lease->property->owner->username }}</td>
            </tr>
            <tr>
                <td>Tenant:</td>
                <td>{{ $lease->tenant->full_name ?? $lease->tenant->username }}</td>
            </tr>
        </table>

        <div class="section-title">2. PROPERTY</div>
        <table class="details-table">
            <tr>
                <td>Address:</td>
                <td>{{ $lease->property->title }}<br>
                    {{ $lease->property->address }}, {{ $lease->property->barangay }}<br>
                    {{ $lease->property->city }}, {{ $lease->property->province }}
                </td>
            </tr>
        </table>

        <div class="section-title">3. TERM AND RENT</div>
        <table class="details-table">
            <tr>
                <td>Lease Start Date:</td>
                <td>{{ \Carbon\Carbon::parse($lease->start_date)->format('F d, Y') }}</td>
            </tr>
            <tr>
                <td>Lease End Date:</td>
                <td>{{ \Carbon\Carbon::parse($lease->end_date)->format('F d, Y') }}</td>
            </tr>
            <tr>
                <td>Monthly Rent:</td>
                <td>PHP {{ number_format($lease->monthly_rent, 2) }}</td>
            </tr>
            <tr>
                <td>Security Deposit:</td>
                <td>PHP {{ number_format($lease->property->security_deposit, 2) }}</td>
            </tr>
        </table>

        <div class="section-title">4. TERMS AND CONDITIONS</div>
        <div class="terms">
            <p><strong>Rent Payment:</strong> The Tenant agrees to pay the Monthly Rent on or before the agreed due date of each month. Late payments may be subject to additional fees as determined by the Landlord.</p>
            <p><strong>Use of Property:</strong> The Property shall be used exclusively as a private residence for the Tenant. Subletting is strictly prohibited unless written consent is provided by the Landlord.</p>
            <p><strong>Maintenance and Repairs:</strong> The Tenant shall maintain the premises in a clean and sanitary condition. Major structural repairs shall be the responsibility of the Landlord unless caused by the negligence of the Tenant.</p>
            <p><strong>Security Deposit:</strong> The Security Deposit shall be held by the Landlord to cover any unpaid rent or damages to the Property beyond normal wear and tear at the end of the Lease Term.</p>
        </div>

        <div class="signatures">
            <div class="signature-box">
                <div class="signature-line"></div>
                <strong>{{ $lease->property->owner->full_name ?? $lease->property->owner->username }}</strong><br>
                Landlord
            </div>
            
            <div class="signature-box" style="float: right;">
                <div class="signature-line">
                    @if($lease->tenant_signature)
                        <img src="{{ $lease->tenant_signature }}" class="signature-img" alt="Tenant Signature">
                    @endif
                </div>
                <strong>{{ $lease->tenant->full_name ?? $lease->tenant->username }}</strong><br>
                Tenant
            </div>
            <div style="clear: both;"></div>
        </div>
    </div>

</body>
</html>

